#!/bin/sh

OWNER=manu

status() {
    if [ $1 = 0 ]; then
        echo 'OK'
    else
        echo 'FAIL'
        exit 1
    fi
}

if [ -f 'manage.py' ]; then
    echo -n 'Recompiling .po files...   '
    python manage.py compilemessages >/dev/null 2>&1
    status $?
fi

echo -n 'Force re-compile of Python bytecode...   '
find -iname '*.py' -exec py_compilefiles -fq {} \;
status $?

echo -n 'Fix permissions of Python bytecode files...   '
find -iname '*.pyc' -exec chown ${OWNER}:${OWNER} {} \;
status $?

echo -n 'Checking web server config...   '
apache2ctl configtest >/dev/null 2>&1
status $?

echo -n 'Reload web server...   '
apache2ctl graceful >/dev/null 2>&1
status $?

